## Configuration file used by the gripper mover

gripper_name: robotiq85_gripper

joint_name:   finger_joint

joint_limits: [0.0, 0.725]  ## rad

vel_limit:    0.825       ## rad/s

acc_limit:    3.5         ## rad/s^2

ctrl_rate:    10.0        ## Hz

inst_target:  false       ## set to false if target is reached by non instantaneous trajectory

tips_strike:  85          ## mm

tcp_closed:   144         ## tcp distance from base_link when closed

tcp_opened:   130         ## tcp distance from base_link when open

# Use the following command to launch the node with the above params
# rosrun robotiq85_gripper robotiq85_gripper gripper_name:="robotiq85_gripper" joint_name:="finger_joint" joint_limits:=[0.0, 0.725] vel_limit:=0.825 _acc_limit:=3.6 ctrl_rate:=10 inst_target:=true tips_strike:=85 tcp_closed:=144 tcp_opened:=130